[package]
name = "mandelzoom"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
sfml = "0.14.0"
structopt = "0.2.18"
palette = "0.4.1"
num_cpus = "1.10.1"
rug = "1.5.2"